# list of packages used in this project

require(ape)
require(broom)
require(dplyr)
require(entropart)
require(GGally)
require(ggplot2)
require(grid)
require(gridExtra)
require(lubridate)
require(magrittr)
require(MASS)
require(minpack.lm)
require(phyloseq)
require(picante)
require(plyr)
require(reshape2)
require(scales)
require(tidyr)
require(vegan)